on:
  workflow_dispatch:
    inputs:
      type:
        description: 'releas diff'
        required: true
        default: 'fix'
        type: choice
        options:
        - break API
        - new feature
        - fix
jobs:
  release:
    runs-on: ubuntu-latest #public
    steps:
    - run: echo ${{ inputs.type }}
    - run: |
        gh -R ${{github.event.repository.full_name}} release ls --json name | python -c '
        import json,sys;print(
          max(
            map(
              lambda __:__[0] ,
              map(lambda __:list(map(int , __["name"].split(".")),
            ) ,
            json.loads(sys.stdin.read()))) ,
          )
          +
          1
        )'
