on:
  workflow_dispatch:
    inputs:
      type:
        description: 'releas diff'
        required: true
        default: 'fix'
        type: choice
        options:
        - break API
        - new feature
        - fix
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  release:
    runs-on: ubuntu-latest #public
    steps:
    - run: echo ${{ inputs.type }}
    - run: |
        gh -R ${{ github.event.repository.full_name }} release ls --json name | python -c '
        import json,sys;
        vlist = map(lambda __:list(map(int , __["name"].split("."))) , json.loads(sys.stdin.read()))
        print(list(vlist))
        '
