on:
  workflow_dispatch:
    inputs:
      type:
        description: 'releas diff'
        required: true
        default: 'fix'
        type: choice
        options:
        - break API
        - new feature
        - fix
      prerelease:
        type: boolean
      draft:
        type: boolean
      title:
        description: 'title'
        required: true
        type: string
      notes:
        description: 'release notes'
        required: false
        type: string
env:
  GH_TOKEN: ${{ secrets.RELEASE_PAT }}
jobs:
  release:
    environment: release
    runs-on: ubuntu-latest #public
    steps:
    - run: echo ${{ inputs.type }}
    - run: |
        gh -R ${{ github.event.repository.full_name }} release ls --json name | python -c '
        import json,sys;
        vlist = list(map(lambda __:list(map(int , __["name"].split("."))) , json.loads(sys.stdin.read())))
        vmax = []
        vmax.append(max(map(lambda __:__[0] , vlist)))
        vmax.append(max(map(lambda __:__[1] , vlist)))
        vmax.append(max(map(lambda __:__[2] , vlist)))
        sys.stdout.write(json.dumps(vmax))
        ' > v.json
    - run: |
        gh -R ${{ github.event.repository.full_name }} \
          release new \
            ${{ inputs.prelease && '-p' }} \
            ${{ inputs.draft && '-d' }} \
            -t "${{ inputs.title }}" \
            -n "${{ inputs.notes }}" \
            --fail-on-no-commits \
            "$(expr $(cat v.json | jq -M '.[0]') + 1).0.0"
      if: ${{ inputs.type == 'break API' }}
