on:
  workflow_dispatch:
    inputs:
      type:
        description: 'releas diff'
        required: true
        default: 'fix'
        type: choice
        options:
        - break API
        - new feature
        - fix
      prerelease:
        type: boolean
      draft:
        type: boolean
      fail-on-no-commits:
        type: boolean
      title:
        description: 'title'
        required: true
        type: string
      notes:
        description: 'release notes'
        required: false
        type: string
env:
  GH_TOKEN: ${{ secrets.RELEASE_PAT }}
jobs:
  release:
    environment: release
    runs-on: ubuntu-latest #public
    steps:
    - run: echo ${{ inputs.type }}
    - run: |
        gh -R ${{ github.event.repository.full_name }} release ls --json name | python -c '
        import json,sys;
        vlist = list(map(lambda __:list(map(int , __["name"].split("."))) , json.loads(sys.stdin.read())))
        vmax = []
        vmax.append(max(map(lambda __:__[0] , vlist)))
        vmax.append(max(map(lambda __:__[1] , vlist)))
        vmax.append(max(map(lambda __:__[2] , vlist)))
        sys.stdout.write(json.dumps(vmax))
        ' > v.json
    - run: printf 'gh' | tee gh
    - run: printf ' --prerelease' | tee --append gh
      if: ${{ inputs.prelease }}
    - run: printf ' --draft' | tee --append gh
      if: ${{ inputs.draft }}
    - run: printf ' --fail-on-no-commits' | tee --append gh
      if: ${{ inputs.fail-on-no-commits }}
    - run: |
        $(cat gh) -R ${{ github.event.repository.full_name }} \
          release new \
            -n "${{ inputs.notes }}" \
            "$(expr $(cat v.json | jq -M '.[0]') + 1).0.0"
      if: ${{ inputs.type == 'break API' }}
