on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  - opened
  - edited
  - auto_merge_enabled
jobs:
  test:
    runs-on: ubuntu-latest #public
    steps:
    - run: docker pull schemers/chicken
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: docker run -v$(realpath .):$(realpath .) -w$(realpath .) -i --rm schemers/chicken chicken-install -test -l .
